server:
  port: 8051

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: wujieprovoid
#eureka客户端注册到eureka服务端
eureka:
  client:
    service-url:
      #单击版eureka
      #defaultZone: http://localhost:8000/eureka/
      #集群版eureka
      defaultZone: http://127.0.0.1:8011/eureka/,http://192.168.11.116:8012/eureka/,http://localhost:8013/eureka/
  instance:
    instance-id: wujieprovoid8051hystrix   #自定义hystrix相关的服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name : wujieprovoid8001
  company.name: www.wujie.com
  build.artifactId: $$project.artifactId$
  build.version: $project.version$

